# Generated by Django 5.1.4 on 2025-06-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updateed_at',
        ),
    ]
